export * from "./atoms";
export * from "./Icon";
export { RatingBadge } from "./RatingBadge";
export { RatingRing } from "./RatingRing";
export { Sparkline } from "./Sparkline";
export { TrendChart } from "./TrendChart";
export { ComparisonBars, type CompareBar } from "./ComparisonBars";
export { KpiCard } from "./KpiCard";
export { Leaderboard } from "./Leaderboard";
export { CalloutCard } from "./Callout";
export { HeroKpiStrip } from "./HeroKpiStrip";
export { SchoolRiskTable } from "./SchoolRiskTable";
export { FrequencyBadge, FreshnessBadge, SourceBadge, KpiMetaRow, DataLagNote } from "./DataBadges";
// ── shared metric grammar (single source of truth) ──
export { FrequencyDelta } from "./FrequencyDelta";
export { NPlusOneLine } from "./NPlusOneLine";
export { ValueDisplay } from "./ValueDisplay";
export { EmptyState } from "./EmptyState";
export { DomainSummaryCard } from "./DomainSummaryCard";
export { GsqacSummaryCard } from "./GsqacSummaryCard";
export { ResponsiveDataTable, type DataColumn } from "./ResponsiveDataTable";
